Repository habx/devops-repo-shared-configs, pull requests merged in 2022-07, with the labels that each got.

#77 APP-30908: fix(renovate): Stability days
  renovate/ts-package-rules.json
Labels: automerge, automerge-delayed-1day

#79 APP-31018: fix(renovate): Dockerfile udpates for clients
  renovate/ts-client.json
Labels: automerge, squash

#81 APP-31085: Group Vite related dependencies update
  renovate/ts-package-rules.json
Labels: automerge, autorelease

#83 APP-31128: chore(renovate): Auto-update containers on clients
  renovate/ts-client.json
Labels: automerge

#84 APP-31167: fix(renovate): Golang package manager
  renovate/go-base.json
Labels: automerge

#85 APP-31292: feat(renovate): Grouping gorm changes
  renovate/go-base.json
Labels: automerge

#86 APP-31302: chore: Delete branch on merge
  github-settings/global.yml
Labels: automerge
