Repository habx/devops-repo-shared-configs, pull requests merged in 2022-05, with the labels that each got.

#46 APP-29479: Adding p-whilst to non-ESM packages list
  renovate/ts-non-esm.json
Labels: automerge

#47 APP-29498: chore: Removing major devDeps automerge
  renovate/ts-service.json
Labels: automerge, automerge-delayed-1day

#48 APP-29725: feat(ghsettings): Adding quash label
  github-settings/global.yml
Labels: automerge, squash

#49 APP-29811: chore: Switching to live updates
  renovate/circleci-orb.json
  renovate/global.json
  renovate/go-base.json
  renovate/renovate-preset.json
  renovate/ts-package-rules.json
Labels: automerge, automerge-delayed-1day

#50 APP-29811: chore(github-settings): Removing node constraint
  renovate/ts-package-rules.json
Labels: automerge, automerge-delayed-2days

#51 APP-29811: chore(renovate): Disabling specific rangeStrategy
  renovate/global.json
Labels: automerge

#53 Revert "APP-29811: chore(renovate): Disabling specific rangeStrategy"
  renovate/global.json
Labels: automerge

#52 APP-29840: Group `@cubejs-client/*` package updates
  renovate/ts-package-rules.json
Labels: automerge

#54 APP-29864: chore(renovate): Switching to PR creation to immediate
  renovate/ts-package-rules.json
Labels: automerge

#56 APP-29876: chore(renovate): StabilityDays / PR Creation behavior change
  renovate/ts-package-rules.json
Labels: automerge

#58 APP-30041: Fixing double rules application
  README.md
  renovate/README.md
  renovate/show-deps.py
  renovate/ts-base.json
Labels: automerge, squash

#59 APP-30046: fix(renovate): TS: legacy-peer-deps=true everywhere
  renovate/README.md
  renovate/ts-client.json
  renovate/ts-lib-client-public.json
  renovate/ts-lib-client.json
  renovate/ts-lib-service.json
  renovate/ts-npmrc-private.json
  renovate/ts-npmrc-public.json
  renovate/ts-service.json
  renovate/ts-tool.json
Labels: automerge

#60 APP-30049: chore(renovate): Adding a go-tool config
  renovate/go-tool.json
Labels: automerge

#61 APP-30050: chore(ghsetings): Adding go-tool
  github-settings/go-tool.yml
Labels: automerge
