Repository habx/devops-repo-shared-configs, pull requests merged in 2022-06, with the labels that each got.

#63 chore(ghsettings): Removing a label oldname (APP-30086)
  github-settings/global.yml
Labels: automerge, automerge-delayed-1day, squash

#66 APP-30186: fix(renovate): orb automerge typo
  renovate/global.json
Labels: automerge

#67 APP-30241: chore(ghsettings): Adding jira-issue label
  github-settings/global.yml
Labels: automerge, squash

#68 APP-30448: fix(renovate): orb upgrade for TS repositories
  renovate/global.json
  renovate/ts-package-rules.json
Labels: automerge, squash

#69 APP-30492: chore(renovate): Adding go-lib
  renovate/go-lib.json
Labels: automerge, squash

#70 APP-30494: chore(renovate): Disabling renovate's automerge for TS
  renovate/ts-base.json
  renovate/ts-client.json
  renovate/ts-lib-client-public.json
  renovate/ts-lib-client.json
  renovate/ts-lib-service.json
  renovate/ts-package-rules.json
  renovate/ts-service.json
  renovate/ts-tool.json
Labels: automerge, squash

#71 APP-30530: feat(renovate): All udpates are squashed
  renovate/global.json
  renovate/ts-package-rules.json
Labels: automerge, squash

#72 APP-30530: feat(renovate): All udpates are squashed
  github-settings/global.yml
Labels: automerge, squash

#73 APP-30713: chore(status-check): update config with new ci
  github-settings/ts-tool.yml
Labels: automerge

#74 APP-30713: chore(ghsettings): Adding last_update for ts-tool
  github-settings/ts-tool.yml
Labels: automerge, squash
