Repository habx/devops-repo-shared-configs, pull requests merged in 2022-08, with the labels that each got.

#88 APP-31464: chore(renovate): More automerge on golang
  renovate/go-base.json
Labels: automerge, squash

#89 APP-31465: chore(renovate): Automerge on some orbs
  renovate/circleci-orb.json
Labels: automerge, squash

#90 chore(renovate): Automerge on some orbs
  renovate/global.json
Labels: automerge, squash, no-jira-issue

#92 APP-31576: Remove job names from required checks
  github-settings/ts-client.yml
Labels: automerge

#93 APP-31598: feature(renovate): Using jsonchema instead of json-spec
  .circleci/config.yml
  github-settings/.yamllint
  github-settings/Pipfile
  github-settings/Pipfile.lock
  renovate/Pipfile
  renovate/Pipfile.lock
Labels: automerge, squash

#94 fix(renovate): Go & Dotnet config update (APP-31634)
  github-settings/dotnet-base.yml
  github-settings/dotnet-lib.yml
  github-settings/go-base.yml
  github-settings/go-lib.yml
  github-settings/go-service-no-codecov.yml
  github-settings/go-service-old.yml
  github-settings/go-service.yml
  github-settings/go-tool.yml
  renovate/README.md
  renovate/dotnet-base.json
  renovate/dotnet-lib.json
Labels: automerge, autorelease, squash

#96 APP-31644: chore(renovate): Freeze lib version
  renovate/dotnet-base.json
Labels: automerge

#97 APP-31645: chore(renovate): Adding a non-ESM package: form-data-encoder
  renovate/ts-non-esm.json
Labels: automerge, squash

#98 chore(renovate): dotnet-lib: Do not override default branch protection rule
  github-settings/dotnet-lib.yml
Labels: automerge, squash

#99 APP-31656: chore(renovate): Adding one more non-ESM package
  renovate/ts-non-esm.json
Labels: automerge, squash

#100 APP-31664: chore(renovate): dotnet: Newtonsoft.Json must stay below 13
  renovate/dotnet-base.json
Labels: automerge, squash

#102 APP-31687: chore(ghsettings): Removing status checks
  github-settings/py-base.yml
Labels: automerge, squash

#103 APP-31726: chore(renovate): Ignoring GraphQL.Client v5
  github-settings/global.yml
  renovate/dotnet-base.json
Labels: automerge, squash

#104 APP-31728: fix(renovate): Stability days
  renovate/ts-package-rules.json
Labels: automerge, squash

#105 APP-31729: chore(renovate): gomod: Adding stabilityDays
  renovate/go-base.json
Labels: automerge, squash

#106 APP-31737: chore(renovate): Adding internal checks filter
  renovate/global.json
  renovate/ts-package-rules.json
Labels: automerge, squash

#107 APP-31748: chore(renovate): Adding internal checks filter
  renovate/global.json
  renovate/ts-non-esm.json
Labels: automerge, squash
